apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: greenapp
  name: greenapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greenapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: greenapp
    spec:
      containers:
      - image: hashicorp/http-echo
        name: http-echo
        resources: {}
        args: ["-text=I am Green", "-listen=0.0.0.0:8081"]
