apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: greenapp
  name: greenapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: greenapp
status:
  loadBalancer: {}
